# Generated by Django 5.0.3 on 2024-03-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0003_dishtype_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishtype",
            name="country",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="dish_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="kitchen_service.dishtype",
            ),
        ),
    ]
