# Generated by Django 5.0.3 on 2024-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0004_dishtype_country_alter_dish_dish_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishtype",
            name="country",
            field=models.CharField(max_length=65, null=True),
        ),
    ]
